import { getMetrics } from "@/actions/metrics";

import {
  Store,
  Wallet,
  ReceiptText,
  Banknote,
} from "lucide-react";

export async function dataCards() {
  const reports = await getMetrics();

  const data = [
    {
      title: "Net Sales",
      value: reports.curr_metrics["Total Revenue"],
      badge: "50%",
      icon: <Store size={20} />,
      past: "+12",
      ratio: false,
    },
    {
      title: "Inventory",
      value: reports.curr_metrics["Inventory"],
      badge: "30%",
      icon: <Wallet size={20} />,
      past: "+8",
      ratio: false,
    },
    {
      title: "Operating Cash Flow",
      value: reports.curr_metrics["Operating Cash Flow"],
      badge: "20%",
      icon: <ReceiptText size={20} />,
      past: "-0.5",
      ratio: false,
    },
    {
      title: "Gross Profit",
      value: reports.curr_metrics["Gross Profit"],
      badge: "10%",
      icon: <Banknote size={20} />,
      past: "+0.2",
      ratio: false,
    },
    {
      title: "Treasury Shares Number",
      value: reports.curr_metrics["Treasury Shares Number"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Ordinary Shares Number",
      value: reports.curr_metrics["Ordinary Shares Number"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Share Issued",
      value: reports.curr_metrics["Share Issued"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Net Debt",
      value: reports.curr_metrics["Net Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Debt",
      value: reports.curr_metrics["Total Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Tangible Book Value",
      value: reports.curr_metrics["Tangible Book Value"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Invested Capital",
      value: reports.curr_metrics["Invested Capital"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Working Capital",
      value: reports.curr_metrics["Working Capital"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Net Tangible Assets",
      value: reports.curr_metrics["Net Tangible Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Capital Lease Obligations",
      value: reports.curr_metrics["Capital Lease Obligations"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Common Stock Equity",
      value: reports.curr_metrics["Common Stock Equity"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Capitalization",
      value: reports.curr_metrics["Total Capitalization"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Equity Gross Minority Interest",
      value: reports.curr_metrics["Total Equity Gross Minority Interest"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Stockholders Equity",
      value: reports.curr_metrics["Stockholders Equity"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Gains Losses Not Affecting Retained Earnings",
      value: reports.curr_metrics["Gains Losses Not Affecting Retained Earnings"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Equity Adjustments",
      value: reports.curr_metrics["Other Equity Adjustments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Retained Earnings",
      value: reports.curr_metrics["Retained Earnings"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Capital Stock",
      value: reports.curr_metrics["Capital Stock"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Common Stock",
      value: reports.curr_metrics["Common Stock"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Common Stock",
      value: reports.curr_metrics["Common Stock"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Liabilities Net Minority Interest",
      value: reports.curr_metrics["Total Liabilities Net Minority Interest"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Non Current Liabilities Net Minority Interest",
      value: reports.curr_metrics["Total Non Current Liabilities Net Minority Interest"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Non Current Liabilities",
      value: reports.curr_metrics["Other Non Current Liabilities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Tradeand Other Payables Non Current",
      value: reports.curr_metrics["Tradeand Other Payables Non Current"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Long Term Debt And Capital Lease Obligation",
      value: reports.curr_metrics["Long Term Debt And Capital Lease Obligation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Long Term Capital Lease Obligation",
      value: reports.curr_metrics["Long Term Capital Lease Obligation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Long Term Debt",
      value: reports.curr_metrics["Long Term Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Current Liabilities",
      value: reports.curr_metrics["Current Liabilities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Current Liabilities",
      value: reports.curr_metrics["Other Current Liabilities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Current Deferred Liabilities",
      value: reports.curr_metrics["Current Deferred Liabilities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Current Debt And Capital Lease Obligation",
      value: reports.curr_metrics["Current Debt And Capital Lease Obligation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Current Capital Lease Obligation",
      value: reports.curr_metrics["Current Capital Lease Obligation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Current Debt",
      value: reports.curr_metrics["Current Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Current Borrowings",
      value: reports.curr_metrics["Other Current Borrowings"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Commercial Paper",
      value: reports.curr_metrics["Commercial Paper"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Payables And Accrued Expenses",
      value: reports.curr_metrics["Payables And Accrued Expenses"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Payables",
      value: reports.curr_metrics["Payables"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Tax Payable",
      value: reports.curr_metrics["Total Tax Payable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Income Tax Payable",
      value: reports.curr_metrics["Income Tax Payable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Accounts Payable",
      value: reports.curr_metrics["Accounts Payable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Assets",
      value: reports.curr_metrics["Total Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Total Non Current Assets",
      value: reports.curr_metrics["Total Non Current Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Non Current Assets",
      value: reports.curr_metrics["Other Non Current Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Non Current Deferred Assets",
      value: reports.curr_metrics["Non Current Deferred Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Other Investments",
      value: reports.curr_metrics["Other Investments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Properties",
      value: reports.curr_metrics["Properties"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "EBITDA",
      value: reports.curr_metrics["EBITDA"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "EBIT",
      value: reports.curr_metrics["EBIT"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Net Interest Income",
      value: reports.curr_metrics["Net Interest Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Net Income",
      value: reports.curr_metrics["Net Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Operating Income",
      value: reports.curr_metrics["Operating Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "-0.9",
      ratio: false,
    },
    {
      title: "Non Current Deferred Taxes Assets",
      value: reports.curr_metrics["Non Current Deferred Taxes Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Investments And Advances",
      value: reports.curr_metrics["Investments And Advances"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Investmentin Financial Assets",
      value: reports.curr_metrics["Investmentin Financial Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Available For Sale Securities",
      value: reports.curr_metrics["Available For Sale Securities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net PPE",
      value: reports.curr_metrics["Net PPE"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Accumulated Depreciation",
      value: reports.curr_metrics["Accumulated Depreciation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Gross PPE",
      value: reports.curr_metrics["Gross PPE"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Leases",
      value: reports.curr_metrics["Leases"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Properties",
      value: reports.curr_metrics["Other Properties"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Machinery Furniture Equipment",
      value: reports.curr_metrics["Machinery Furniture Equipment"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Land And Improvements",
      value: reports.curr_metrics["Land And Improvements"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Current Assets",
      value: reports.curr_metrics["Current Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Current Assets",
      value: reports.curr_metrics["Other Current Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Receivables",
      value: reports.curr_metrics["Receivables"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Receivables",
      value: reports.curr_metrics["Other Receivables"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Accounts Receivable",
      value: reports.curr_metrics["Accounts Receivable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Cash Equivalents And Short Term Investments",
      value: reports.curr_metrics["Cash Cash Equivalents And Short Term Investments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Short Term Investments",
      value: reports.curr_metrics["Other Short Term Investments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash And Cash Equivalents",
      value: reports.curr_metrics["Cash And Cash Equivalents"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Equivalents",
      value: reports.curr_metrics["Cash Equivalents"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Financial",
      value: reports.curr_metrics["Cash Financial"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Tax Effect Of Unusual Items",
      value: reports.curr_metrics["Tax Effect Of Unusual Items"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Tax Rate For Calcs",
      value: reports.curr_metrics["Tax Rate For Calcs"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Normalized EBITDA",
      value: reports.curr_metrics["Normalized EBITDA"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income From Continuing Operation Net Minority Interest",
      value: reports.curr_metrics["Net Income From Continuing Operation Net Minority Interest"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Reconciled Depreciation",
      value: reports.curr_metrics["Reconciled Depreciation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Reconciled Cost Of Revenue",
      value: reports.curr_metrics["Reconciled Cost Of Revenue"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Interest Expense",
      value: reports.curr_metrics["Interest Expense"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Interest Income",
      value: reports.curr_metrics["Interest Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Normalized Income",
      value: reports.curr_metrics["Normalized Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income From Continuing And Discontinued Operation",
      value: reports.curr_metrics["Net Income From Continuing And Discontinued Operation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Total Expenses",
      value: reports.curr_metrics["Total Expenses"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Total Operating Income As Reported",
      value: reports.curr_metrics["Total Operating Income As Reported"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Diluted Average Shares",
      value: reports.curr_metrics["Diluted Average Shares"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Basic Average Shares",
      value: reports.curr_metrics["Basic Average Shares"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Diluted EPS",
      value: reports.curr_metrics["Diluted EPS"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Basic EPS",
      value: reports.curr_metrics["Basic EPS"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Diluted NI Availto Com Stockholders",
      value: reports.curr_metrics["Diluted NI Availto Com Stockholders"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income Common Stockholders",
      value: reports.curr_metrics["Net Income Common Stockholders"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income Including Noncontrolling Interests",
      value: reports.curr_metrics["Net Income Including Noncontrolling Interests"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income Continuous Operations",
      value: reports.curr_metrics["Net Income Continuous Operations"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Tax Provision",
      value: reports.curr_metrics["Tax Provision"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Pretax Income",
      value: reports.curr_metrics["Pretax Income"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Income Expense",
      value: reports.curr_metrics["Other Income Expense"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Non Operating Income Expenses",
      value: reports.curr_metrics["Other Non Operating Income Expenses"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Non Operating Interest Income Expense",
      value: reports.curr_metrics["Net Non Operating Interest Income Expense"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Interest Expense Non Operating",
      value: reports.curr_metrics["Interest Expense Non Operating"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Interest Income Non Operating",
      value: reports.curr_metrics["Interest Income Non Operating"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Operating Expense",
      value: reports.curr_metrics["Operating Expense"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Research And Development",
      value: reports.curr_metrics["Research And Development"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Selling General And Administration",
      value: reports.curr_metrics["Selling General And Administration"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cost Of Revenue",
      value: reports.curr_metrics["Cost Of Revenue"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Operating Revenue",
      value: reports.curr_metrics["Operating Revenue"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Free Cash Flow",
      value: reports.curr_metrics["Free Cash Flow"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Repurchase Of Capital Stock",
      value: reports.curr_metrics["Repurchase Of Capital Stock"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Repayment Of Debt",
      value: reports.curr_metrics["Repayment Of Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Issuance Of Debt",
      value: reports.curr_metrics["Issuance Of Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Issuance Of Capital Stock",
      value: reports.curr_metrics["Issuance Of Capital Stock"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Capital Expenditure",
      value: reports.curr_metrics["Capital Expenditure"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Interest Paid Supplemental Data",
      value: reports.curr_metrics["Interest Paid Supplemental Data"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Income Tax Paid Supplemental Data",
      value: reports.curr_metrics["Income Tax Paid Supplemental Data"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "End Cash Position",
      value: reports.curr_metrics["End Cash Position"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Beginning Cash Position",
      value: reports.curr_metrics["Beginning Cash Position"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Changes In Cash",
      value: reports.curr_metrics["Changes In Cash"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Financing Cash Flow",
      value: reports.curr_metrics["Financing Cash Flow"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Flow From Continuing Financing Activities",
      value: reports.curr_metrics["Cash Flow From Continuing Financing Activities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Other Financing Charges",
      value: reports.curr_metrics["Net Other Financing Charges"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Dividends Paid",
      value: reports.curr_metrics["Cash Dividends Paid"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Common Stock Dividend Paid",
      value: reports.curr_metrics["Common Stock Dividend Paid"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Common Stock Issuance",
      value: reports.curr_metrics["Net Common Stock Issuance"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Common Stock Payments",
      value: reports.curr_metrics["Common Stock Payments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Common Stock Issuance",
      value: reports.curr_metrics["Common Stock Issuance"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "",
      value: reports.curr_metrics[""],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Issuance Payments Of Debt",
      value: reports.curr_metrics["Net Issuance Payments Of Debt"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Short Term Debt Issuance",
      value: reports.curr_metrics["Net Short Term Debt Issuance"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Long Term Debt Issuance",
      value: reports.curr_metrics["Net Long Term Debt Issuance"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Long Term Debt Payments",
      value: reports.curr_metrics["Long Term Debt Payments"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Long Term Debt Issuance",
      value: reports.curr_metrics["Long Term Debt Issuance"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Investing Cash Flow",
      value: reports.curr_metrics["Investing Cash Flow"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Flow From Continuing Investing Activities",
      value: reports.curr_metrics["Cash Flow From Continuing Investing Activities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Other Investing Changes",
      value: reports.curr_metrics["Net Other Investing Changes"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Investment Purchase And Sale",
      value: reports.curr_metrics["Net Investment Purchase And Sale"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Sale Of Investment",
      value: reports.curr_metrics["Sale Of Investment"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Purchase Of Investment",
      value: reports.curr_metrics["Purchase Of Investment"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Business Purchase And Sale",
      value: reports.curr_metrics["Net Business Purchase And Sale"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Purchase Of Business",
      value: reports.curr_metrics["Purchase Of Business"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net PPE Purchase And Sale",
      value: reports.curr_metrics["Net PPE Purchase And Sale"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Purchase Of PPE",
      value: reports.curr_metrics["Purchase Of PPE"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Cash Flow From Continuing Operating Activities",
      value: reports.curr_metrics["Cash Flow From Continuing Operating Activities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Working Capital",
      value: reports.curr_metrics["Change In Working Capital"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Other Working Capital",
      value: reports.curr_metrics["Change In Other Working Capital"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Other Current Liabilities",
      value: reports.curr_metrics["Change In Other Current Liabilities"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Other Current Assets",
      value: reports.curr_metrics["Change In Other Current Assets"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Payables And Accrued Expense",
      value: reports.curr_metrics["Change In Payables And Accrued Expense"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Payable",
      value: reports.curr_metrics["Change In Payable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Account Payable",
      value: reports.curr_metrics["Change In Account Payable"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Inventory",
      value: reports.curr_metrics["Change In Inventory"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Change In Receivables",
      value: reports.curr_metrics["Change In Receivables"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Changes In Account Receivables",
      value: reports.curr_metrics["Changes In Account Receivables"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Other Non Cash Items",
      value: reports.curr_metrics["Other Non Cash Items"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Stock Based Compensation",
      value: reports.curr_metrics["Stock Based Compensation"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Deferred Tax",
      value: reports.curr_metrics["Deferred Tax"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Deferred Income Tax",
      value: reports.curr_metrics["Deferred Income Tax"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Depreciation Amortization Depletion",
      value: reports.curr_metrics["Depreciation Amortization Depletion"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Depreciation And Amortization",
      value: reports.curr_metrics["Depreciation And Amortization"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
    {
      title: "Net Income From Continuing Operations",
      value: reports.curr_metrics["Net Income From Continuing Operations"],
      badge: "2%",
      icon: <ReceiptText size={20} />,
      past: "+0.9",
      ratio: false,
    },
  ]

  return data;
}